name: Extract ZIP file name

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  identify-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: List files in the directory
      run: ls -1 > files.txt

    - name: Find ZIP file and store the names
      run: |
        zip_file=$(grep -E '\.zip$' files.txt || echo "")
        if [ -z "$zip_file" ]; then
          echo "No ZIP file found."
          exit 0
        fi
        zip_file_without_ext="${zip_file%.zip}"
        echo "ZIP_FILE_NAME=$zip_file" >> $GITHUB_ENV
        echo "ZIP_FILE_NAME_WITHOUT_EXT=$zip_file_without_ext" >> $GITHUB_ENV

    - name: Display the variables
      if: env.ZIP_FILE_NAME != ''
      run: |
        echo "ZIP File Name with extension: ${{ env.ZIP_FILE_NAME }}"
        echo "ZIP File Name without extension: ${{ env.ZIP_FILE_NAME_WITHOUT_EXT }}"

    - name: Install unzip
      run: sudo apt-get install unzip -y

    - name: Extract ZIP Files
      run: unzip "${{ env.ZIP_FILE_NAME }}" -d extracted-directory

    - name: Find all POM files
      id: find_poms
      run: |
        find extracted-directory -type f -name "pom.xml" > pom_paths.txt
        cat pom_paths.txt

    - name: Extract groupId from POM parent element
      run: |
        while IFS= read -r pom_path; do
          echo "Processing $pom_path"
          group_id_line=$(grep -A 2 '<parent>' "$pom_path" | grep '<groupId>' | head -n 1)
          group_id=$(echo "$group_id_line" | sed -e 's/.*<groupId>\(.*\)<\/groupId>.*/\1/')
          echo "Parent groupId: $group_id"
          echo "$group_id" >> group_ids.txt
        done < pom_paths.txt

    - name: Print all extracted groupIds
      run: |
        echo "Extracted groupIds:"
        cat group_ids.txt
